import { type Recipe } from '@/app/recipe/[id]'; // Assuming Recipe type is exported from [id].tsx or a types file

export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Classic Tomato Pasta',
    description: 'A simple yet delicious pasta dish with a rich tomato sauce.',
    cookTime: 20,
    prepTime: 10,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'Italian',
    ingredients: [
      { id: 'i1', name: 'Spaghetti', amount: '200g' },
      { id: 'i2', name: 'Canned Tomatoes', amount: '400g' },
      { id: 'i3', name: 'Garlic', amount: '2 cloves, minced' },
      { id: 'i4', name: 'Olive Oil', amount: '2 tbsp' },
      { id: 'i5', name: 'Basil', amount: 'a few leaves' },
      { id: 'i6', name: 'Salt', amount: 'to taste' },
      { id: 'i7', name: 'Pepper', amount: 'to taste' },
    ],
    steps: [
      { id: 's1', step: 1, description: 'Cook spaghetti according to package directions.' },
      { id: 's2', step: 2, description: 'While pasta cooks, heat olive oil in a pan. Add garlic and cook until fragrant.' },
      { id: 's3', step: 3, description: 'Add canned tomatoes, basil, salt, and pepper. Simmer for 10 minutes.' },
      { id: 's4', step: 4, description: 'Drain pasta and add to the sauce. Toss to combine.' },
      { id: 's5', step: 5, description: 'Serve immediately with a sprinkle of Parmesan if desired.' },
    ],
    image: 'https://images.unsplash.com/photo-1598866594240-a7161916025e', // Placeholder
    isSaved: false,
    rating: 4.5,
    calories: 350,
    protein: 12,
    mealType: 'Dinner',
  },
  {
    id: '2',
    title: 'Spicy Chicken Stir-fry',
    description: 'A quick and flavorful chicken stir-fry with a spicy kick.',
    cookTime: 25,
    prepTime: 20,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'Asian',
    ingredients: [
      { id: 'c1', name: 'Chicken Breast', amount: '500g, sliced' },
      { id: 'c2', name: 'Soy Sauce', amount: '3 tbsp' },
      { id: 'c3', name: 'Broccoli Florets', amount: '1 head' },
      { id: 'c4', name: 'Red Bell Pepper', amount: '1, sliced' },
      { id: 'c5', name: 'Garlic', amount: '3 cloves, minced' },
      { id: 'c6', name: 'Ginger', amount: '1 inch, grated' },
      { id: 'c7', name: 'Chili Flakes', amount: '1 tsp (or to taste)' },
    ],
    steps: [
      { id: 'cs1', step: 1, description: 'Marinate chicken slices with soy sauce for 15 minutes.' },
      { id: 'cs2', step: 2, description: 'Heat oil in a wok or large skillet. Add garlic and ginger, stir-fry until fragrant.' },
      { id: 'cs3', step: 3, description: 'Add chicken and cook until browned and cooked through.' },
      { id: 'cs4', step: 4, description: 'Add broccoli and bell pepper. Stir-fry for 5-7 minutes until tender-crisp.' },
      { id: 'cs5', step: 5, description: 'Sprinkle with chili flakes. Mix well and serve hot with rice or noodles.' },
    ],
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3', // Placeholder
    isSaved: true,
    rating: 4,
    calories: 450,
    protein: 35,
    mealType: 'Dinner',
  },
  {
    id: '3',
    title: 'Avocado Toast with Egg',
    description: 'A healthy and satisfying breakfast or light meal.',
    cookTime: 10,
    prepTime: 5,
    servings: 1,
    difficulty: 'Easy',
    cuisine: 'Modern',
    ingredients: [
      { id: 'a1', name: 'Whole-wheat Bread', amount: '2 slices' },
      { id: 'a2', name: 'Avocado', amount: '1 ripe' },
      { id: 'a3', name: 'Egg', amount: '1 or 2' },
      { id: 'a4', name: 'Red Pepper Flakes', amount: 'a pinch' },
      { id: 'a5', name: 'Salt', amount: 'to taste' },
      { id: 'a6', name: 'Pepper', amount: 'to taste' },
    ],
    steps: [
      { id: 'as1', step: 1, description: 'Toast bread slices to your liking.' },
      { id: 'as2', step: 2, description: 'Mash avocado in a bowl. Season with salt and pepper.' },
      { id: 'as3', step: 3, description: 'Cook egg as desired (fried, poached, or scrambled).' },
      { id: 'as4', step: 4, description: 'Spread mashed avocado on toast. Top with cooked egg.' },
      { id: 'as5', step: 5, description: 'Sprinkle with red pepper flakes and serve immediately.' },
    ],
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8', // Placeholder
    isSaved: false,
    rating: 5,
    calories: 300,
    protein: 15,
    mealType: 'Lunch', // Set as Lunch
  },
  // Added more recipes to match Today's Picks from home screen
  {
    id: '4',
    title: 'Chicken Caesar Salad',
    description: 'Fresh romaine lettuce with grilled chicken, croutons, and caesar dressing',
    cookTime: 20,
    prepTime: 10,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'American',
    ingredients: [
      { id: 'cs1', name: 'Chicken Breast', amount: '2, grilled and sliced' },
      { id: 'cs2', name: 'Romaine Lettuce', amount: '1 head, chopped' },
      { id: 'cs3', name: 'Croutons', amount: '1 cup' },
      { id: 'cs4', name: 'Parmesan Cheese', amount: '1/4 cup, grated' },
      { id: 'cs5', name: 'Caesar Dressing', amount: '1/4 cup' },
      { id: 'cs6', name: 'Black Pepper', amount: 'to taste' },
    ],
    steps: [
      { id: 'css1', step: 1, description: 'Grill chicken breasts until fully cooked. Let rest then slice.' },
      { id: 'css2', step: 2, description: 'Wash and chop romaine lettuce, place in a large bowl.' },
      { id: 'css3', step: 3, description: 'Add sliced chicken, croutons, and grated Parmesan.' },
      { id: 'css4', step: 4, description: 'Drizzle with Caesar dressing and toss to combine.' },
      { id: 'css5', step: 5, description: 'Season with black pepper and serve immediately.' },
    ],
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
    isSaved: false,
    rating: 4.7,
    calories: 320,
    protein: 28,
    mealType: 'Lunch',
  },
  {
    id: '5',
    title: 'Vegetable Stir Fry',
    description: 'Quick and healthy vegetable stir fry with your favorite veggies',
    cookTime: 15,
    prepTime: 10,
    servings: 2,
    difficulty: 'Easy',
    cuisine: 'Asian',
    ingredients: [
      { id: 'vf1', name: 'Broccoli', amount: '1 cup, florets' },
      { id: 'vf2', name: 'Carrots', amount: '2, sliced' },
      { id: 'vf3', name: 'Bell Peppers', amount: '1, sliced' },
      { id: 'vf4', name: 'Snow Peas', amount: '1 cup' },
      { id: 'vf5', name: 'Garlic', amount: '2 cloves, minced' },
      { id: 'vf6', name: 'Soy Sauce', amount: '2 tbsp' },
      { id: 'vf7', name: 'Sesame Oil', amount: '1 tbsp' },
    ],
    steps: [
      { id: 'vfs1', step: 1, description: 'Heat sesame oil in a wok or large pan over medium-high heat.' },
      { id: 'vfs2', step: 2, description: 'Add minced garlic and stir for 30 seconds until fragrant.' },
      { id: 'vfs3', step: 3, description: 'Add broccoli and carrots, stir-fry for 3 minutes.' },
      { id: 'vfs4', step: 4, description: 'Add bell peppers and snow peas, cook for another 2 minutes.' },
      { id: 'vfs5', step: 5, description: 'Add soy sauce, toss to coat, and serve hot.' },
    ],
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19',
    isSaved: false,
    rating: 4.5,
    calories: 180,
    protein: 6,
    mealType: 'Lunch',
  },
  {
    id: '6',
    title: 'Margherita Pizza',
    description: 'Classic pizza with tomato, mozzarella, and fresh basil',
    cookTime: 30,
    prepTime: 15,
    servings: 4,
    difficulty: 'Medium',
    cuisine: 'Italian',
    ingredients: [
      { id: 'mp1', name: 'Pizza Dough', amount: '1 ball (300g)' },
      { id: 'mp2', name: 'Tomato Sauce', amount: '1/2 cup' },
      { id: 'mp3', name: 'Fresh Mozzarella', amount: '200g, sliced' },
      { id: 'mp4', name: 'Fresh Basil', amount: '10 leaves' },
      { id: 'mp5', name: 'Olive Oil', amount: '2 tbsp' },
      { id: 'mp6', name: 'Salt', amount: 'to taste' },
    ],
    steps: [
      { id: 'mps1', step: 1, description: 'Preheat oven to 475°F (245°C) with a pizza stone if available.' },
      { id: 'mps2', step: 2, description: 'Roll out the pizza dough to your desired thickness.' },
      { id: 'mps3', step: 3, description: 'Spread tomato sauce evenly over the dough.' },
      { id: 'mps4', step: 4, description: 'Arrange mozzarella slices on top and drizzle with olive oil.' },
      { id: 'mps5', step: 5, description: 'Bake for 10-12 minutes until crust is golden and cheese is bubbly.' },
      { id: 'mps6', step: 6, description: 'Add fresh basil leaves after baking, slice and serve.' },
    ],
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
    isSaved: false,
    rating: 4.8,
    calories: 280,
    protein: 15,
    mealType: 'Dinner',
  }
];

// Helper function to get a recipe by ID
export const getMockRecipeById = (recipeId: string): Recipe | undefined => {
  return MOCK_RECIPES.find(recipe => recipe.id === recipeId);
};
