/**
 * A list of common ingredients for autocomplete suggestions
 */
export const commonIngredients = [
  // Proteins
  'chicken',
  'beef',
  'pork',
  'shrimp',
  'salmon',
  'tuna',
  'tofu',
  'eggs',
  'turkey',
  'lamb',
  'bacon',
  'sausage',
  'ground beef',
  'ground turkey',
  'chicken breast',
  'chicken thighs',

  // Vegetables
  'onion',
  'garlic',
  'tomato',
  'potato',
  'carrot',
  'bell pepper',
  'broccoli',
  'spinach',
  'lettuce',
  'cucumber',
  'zucchini',
  'mushroom',
  'corn',
  'green beans',
  'peas',
  'cauliflower',
  'asparagus',
  'kale',
  'cabbage',
  'sweet potato',
  'eggplant',
  'celery',

  // Fruits
  'apple',
  'banana',
  'orange',
  'lemon',
  'lime',
  'strawberry',
  'blueberry',
  'raspberry',
  'blackberry',
  'mango',
  'pineapple',
  'avocado',
  'grapes',
  'watermelon',
  'peach',
  'pear',
  'cherry',
  'kiwi',

  // Grains & Pasta
  'rice',
  'pasta',
  'noodles',
  'bread',
  'quinoa',
  'couscous',
  'oats',
  'flour',
  'tortilla',
  'pita',
  'bulgur',
  'barley',

  // Dairy & Alternatives
  'milk',
  'cheese',
  'butter',
  'yogurt',
  'cream',
  'sour cream',
  'cream cheese',
  'parmesan',
  'cheddar',
  'mozzarella',
  'feta',
  'goat cheese',
  'almond milk',
  'oat milk',
  'coconut milk',

  // Herbs & Spices
  'salt',
  'pepper',
  'basil',
  'oregano',
  'thyme',
  'rosemary',
  'cilantro',
  'parsley',
  'dill',
  'mint',
  'cumin',
  'paprika',
  'chili powder',
  'cinnamon',
  'ginger',
  'turmeric',
  'curry powder',
  'bay leaf',
  'sage',

  // Condiments & Sauces
  'olive oil',
  'vegetable oil',
  'soy sauce',
  'vinegar',
  'hot sauce',
  'ketchup',
  'mustard',
  'mayonnaise',
  'honey',
  'maple syrup',
  'salsa',
  'pesto',
  'barbecue sauce',
  'teriyaki sauce',
  'sriracha',
  'tahini',

  // Nuts & Seeds
  'almonds',
  'walnuts',
  'peanuts',
  'cashews',
  'sunflower seeds',
  'chia seeds',
  'flax seeds',
  'sesame seeds',
  'pine nuts',
  'pumpkin seeds',

  // Legumes
  'beans',
  'black beans',
  'chickpeas',
  'lentils',
  'pinto beans',
  'kidney beans',
  'edamame',

  // Baking
  'sugar',
  'brown sugar',
  'baking powder',
  'baking soda',
  'vanilla extract',
  'chocolate chips',
  'cocoa powder',
  'yeast',
];

export const popularCombinations = [
  {
    id: '1',
    name: 'Pasta Dinner',
    ingredients: ['pasta', 'tomatoes', 'garlic', 'olive oil', 'basil'],
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
  },
  {
    id: '2',
    name: 'Taco Night',
    ingredients: ['ground beef', 'tortilla', 'onion', 'tomato', 'lettuce', 'cheese'],
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
  },
  {
    id: '3',
    name: 'Stir Fry',
    ingredients: ['chicken', 'broccoli', 'bell pepper', 'soy sauce', 'rice'],
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
  },
  {
    id: '4',
    name: 'Breakfast',
    ingredients: ['eggs', 'bacon', 'bread', 'avocado', 'tomato'],
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
  },
  {
    id: '5',
    name: 'Soup',
    ingredients: ['chicken', 'carrot', 'celery', 'onion', 'noodles'],
    image: 'https://images.unsplash.com/photo-1603105037303-f0b9629d3a34?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80',
  },
]; 